### ISSUE TITLE
Addition of parental samples to existing sample

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/cgadmin#11]
Unable to use same family no - have to change to another fam no

**Comment by robinandeer** [comment]
You should be able to check "Existing family" and provide the same family id

Otherwise can you provide an example of when it's not working?

**Comment by KickiLagerstedt** [comment]
Did not see that little box...

**Comment by robinandeer** [comment]
Oki, we will continue to work on the interface and make it easier to use

For now we are mostly concerned with having all the functionality in place :)
