### ISSUE TITLE
Wrong format

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/cgadmin#15]
Sometimes You get an error that You have submitted something in the wrong format - would be nice to know what the correct format is i.e. "do not use /_?" etc

**Comment by robinandeer** [comment]
Yes indeed - this is something we have to iterate on to become better and better at 👍 

Can you provide an example of when this is happening? Then I will look into it!

**Comment by KickiLagerstedt** [comment]
I tried to name a family F000XXXX_2 - did not work. 
F000XXX-2 did work

I think it was the same with project name

**Comment by robinandeer** [comment]
Aha, the project name you should be able to name however you want - I will remove the restrictions there!

The family name is used in the analysis and needs to follow some rules - I will make the error more clear - thanks for the feedback btw!!

**Comment by KickiLagerstedt** [comment]
😄
