### ISSUE TITLE
How can I keep track of my orders?

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/cgadmin#16]
Upon submitting an order I can not see a list or anything regarding submitted orders.
- Would be nice to recieve an email with ticket no
- See a list regarding submitted oders
- See the orders in Support center

Right now I have no idea if the order is submitted or not...

**Comment by robinandeer** [comment]
Hmm.. I could keep the submitted order in the list I guess. At least for a while.

You should receive an email with the link to the associated ticket to the email you are using to login - is this not working?

We are thinking of a better way for you to view tickets in the support center software - stay tuned and we'll hopefully have a better way for you to search for orders!

**Comment by KickiLagerstedt** [comment]
I have not recieved an email! - that would be great if that worked.

**Comment by robinandeer** [comment]
I see what's happening. You are logged in to the order portal with your Scout email which is where the confirmation email is sent.

As I see we have a few options:

1. Log into the gmail using your Scout account.
2. Use a different Google account which you more regularly check email for - do you have one of those?
3. Setup [email forwarding](https://support.google.com/mail/answer/10957?hl=en) from your Scout account to forward all emails there to e.g. your KI email

Please let us know if any of those options works for you or we'll work out a different solution

**Comment by KickiLagerstedt** [comment]
OK 
I have fixed according to nr 3...

**Comment by robinandeer** [comment]
Good! Tell us if you still don't get the confirmation emails

I've also updated the server to display already submitted orders
