### ISSUE TITLE
No notification regarding making a new order

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/cgadmin#27]
Had a discussion with Robin regarding this yesterday, and everything should have been fixed.

Unfortionatelly I still do not get an email when I have created an order/ticket

// Kicki

**Comment by ingkebil** [comment]
Hi kicki,

this should be fixed now! The problem lied in our automatic detection of ticket numbers in the name of the order which picked up your family instead. This caused no tickets to be opened and orders to be submitted with the ticket id pointing to a family.

wkr,
Kenny
