### ISSUE TITLE
Can not submit order.... 

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/cgadmin#29]
Unable to submit order... 
![bild](https://user-images.githubusercontent.com/17139607/33268220-bba4a048-d37c-11e7-8231-b4f95174fa72.png)

**Comment by KickiLagerstedt** [comment]
Kommer inte längre... Kan trycka hur många ggr som hellst på "Are you sure"

**Comment by ingkebil** [comment]
Hi kicki,

this has now been fixed,

wkr,
kenny
