### ISSUE TITLE
Can not save sample - can not submit order...

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/cgadmin#31]
Trodde att denna skulle fungera i och med att det inte var något krångel med detta prov - men icke sa nicke...

![bild](https://user-images.githubusercontent.com/17139607/33268778-c1ab85fe-d37e-11e7-86bd-1b4aaef8ab1c.png)

**Comment by ingkebil** [comment]
Hi kicki! You can click "save" again now! :)

There is another issue that the website seems to be hanging on the "Are you sure?" button after you have clicked it. The order is submitted tho and I am investigating what might be wrong. You can check on the "status" tab if the samples are registered. If you are unsure the order came through, please open an additional ticket for now.
If all goes well, I will have fixed this by tomorrow evening,

wkr,
Kenny

**Comment by KickiLagerstedt** [comment]
Tried to submit an sample - Still "Are You sure?" Pressed four times...

<OwaStorableObject type="Items" version="1" denyCopy="false" denyMove="false"><Items FolderId="LgAAAADQamSuRAzqSq7aIimh4DjaAQDzr7DjoP8fRIM8Fsee1U9yAEviDQaZAAAB" IsCrossFolder="false"><Item ItemId="RgAAAADQamSuRAzqSq7aIimh4DjaBwDzr7DjoP8fRIM8Fsee1U9yAEviDQaZAADHPwgLaTa4QZv0dP7mppKzAAFIoN8WAAAJ" ItemType="IPM.Note"/></Items></OwaStorableObject>
![bild](https://user-images.githubusercontent.com/17139607/33371267-6e840cc0-d4fa-11e7-8214-c2deeb615e48.png)

**Comment by KickiLagerstedt** [comment]
4 times...
![bild](https://user-images.githubusercontent.com/17139607/33371341-aa177f92-d4fa-11e7-91f5-d5c8932b1e9b.png)

**Comment by KickiLagerstedt** [comment]
Can You send me the link to this ticket??? // Thanks

**Comment by ingkebil** [comment]
Hi kicki,

this is now completely fixed. "Are you sure" only appears once :) I'll send you the ticket id in a minute,

wkr,
Kenny

**Comment by ingkebil** [comment]
This is the ticket nr #640384.

I will update the order portal so it links to the correct ticket,
