### ISSUE TITLE
When adding two children their parents, only parents for one child is saved

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cgadmin#5]
Happens in the project page as well as when editing a sample in the admin interface.

**Comment by ingkebil** [comment]
See project 22

**Comment by ingkebil** [comment]
ok, this is the weirdest error ever.

If you edit a sample, the parents ids are not always filled in, even though they are filled in in the database!
see `/admin/sample/edit/?id=39` and `/admin/sample/edit/?id=38`

**Comment by ingkebil** [comment]
Additionally: on the project view, the Father column it off by one (shifted up one)

**Comment by ingkebil** [comment]
The relationship is stored really weirdly in the database.

The parents mark themsellves as mother/father of a child, allowing for only one child. The columns are still named mother_id and father_id, even though they are pointing to a child.

**Comment by robinandeer** [comment]
ohh whoops - I might have been trying to look like the ped format too much

**Comment by robinandeer** [comment]
I think the reason why the first issue comes up is that the session isn't properly refreshed

**Comment by ingkebil** [comment]
Yeah, the first issue is really a bit random, so improperly refreshed session seems like a plausible cause. Sometimes the parents are filled in, sometimes not.

Didn't want to touch the second issue. Didn't want to figure figure out what other logic was depending on the parents linking to the children instead of vice-versa.

**Comment by ingkebil** [comment]
Fixed in 6902a75d0602aacb90eceb5111b9d6779fbbc198
