### ISSUE TITLE
Project details, Order portal BETA

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/cgadmin#9]
Från Kicki:
Kan inte skapa "Project details" och vet ej heller hur det ska skapas. Rutan som ska beskriva detta är tom:

**Comment by moonso** [comment]
Svar från @robinandeer:

Hej!

Vad bra att du hjälper oss att testa portalen 👍 

Enligt [instruktionerna](http://www.clinicalgenomics.se/bestallningar/):

> Fill in the ticket ID that you copied in Step 1 as the “Project name”.

Du kan döpa din ticket i SupportSystems till vad du vill men iaf för nu:

1. öppna en ticket i SupportSystems
2. kopiera ticket id:t och ange det som "Project name" i orderportalen

**Comment by robinandeer** [comment]
done!
